### ISSUE TITLE
Sensor stops working - 'Entering config mode failed'

### ISSUE THREAD

**Issue by martinmasera** [TillFleisch/ESPHome-HLK-LD2450#12]
esp8266 and LD2450 sensor,
everything looks to work fine by after 5 or 10 minuts the sensor do not work any more, 
can you please check or do you know what can be an issue.

[logs_esp8_run (1).txt](https://github.com/TillFleisch/ESPHome-HLK-LD2450/files/15344321/logs_esp8_run.1.txt)

**Comment by TillFleisch** [comment]
Make sure the sensors TX pin is also connected and ensure that RX/TX lines are wired correctly.
This sounds like a power-issue, please refer to the Troubleshooting section of the README for further information.
Furthermore, make sure that the sensors firmware is up to date, as older firmware may not support sensor configuration (I am currently using `V2.04.23101915`).

**Comment by martinmasera** [comment]
Thanks for info,

**Comment by TillFleisch** [comment]
@barbiermathieu91 are you supplying the sensor with 5V?

**Comment by martinmasera** [comment]
All works now. Yea 5v.

**Comment by barbiermathieu91** [comment]
Yes I have checked.
The one that was blocked get 5.3v and another one that I noticed was stucked gets 5v

**Comment by TillFleisch** [comment]
@barbiermathieu91, when the sensor is "stuck", does the HLK App still work?
Are you by any chance using long wires? Clean power and reliable communication can also be affected by this.

**Comment by barbiermathieu91** [comment]
I think HLK app is not working (I will check it)
I am using wires provided with the sensor, less than 10cm

**Comment by TillFleisch** [comment]
It sound like the sensor is getting stuck. Try updating the sensors firmware and using a different power supply or using a different(replacement) sensor.

I will close this as not planned since it does not seem like an issue with this component. We can continue this discussion here if there are further problems.
